version: "3"

services:

  runtime-setup:
    image: prometheus:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"

  documentation-check:
    image: prometheus:22.04-5.8

  test:
    image: prometheus:22.04-5.8
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      #- SANITIZER_ARG=--sanitize=thread

  update-benchmark-baseline:
    image: prometheus:22.04-5.8
    environment:
      - SWIFT_VERSION=5.8

  shell:
    image: prometheus:22.04-5.8
